function MovableBlock(el){
    var _this=this;
    if(!el){
        console.error('元素无效');
        return
    }
    _this.el=el;
    _this.pos={
        xCur:NaN,
        yCur:NaN,
        xOffset:NaN,
        yOffset:NaN,
        xNew:NaN,
        yNew:NaN
    }
    MovableBlock.prototype.init=function(){
        _this.pos.xCur=_this.el.offsetLeft;
        _this.pos.yCur=_this.el.offsetTop;
        _this.el.addEventListener('mousedown',_this.startMoveBind,false);
        _this.el.addEventListener('dblclick',_this.close,false);
    }
    MovableBlock.prototype.startMove=function(e){
        _this.pos.xCur=_this.el.offsetLeft;
        _this.pos.yCur=_this.el.offsetTop;
        _this.pos.xOffset=e.clientX-_this.pos.xCur;
        _this.pos.yOffset=e.clientY-_this.pos.yCur;
        document.body.addEventListener('mousemove',_this.movingBind,false);
        document.body.addEventListener('mouseup',_this.endMoveBind,false);
    }
    MovableBlock.prototype.moving=function(e){
        console.log(e);
        _this.pos.xNew=e.clientX-_this.pos.xOffset;
        _this.pos.yNew=e.clientY-_this.pos.yOffset;
        _this.el.style.top=_this.pos.yNew+'px';
        _this.el.style.left=_this.pos.xNew+'px';
    }
    MovableBlock.prototype.endMove=function(e){
        document.body.removeEventListener('mousemove',_this.movingBind,false);
        document.body.removeEventListener('mouseup',_this.endMoveBind,false);
        _this.el.style.top=_this.pos.yNew+'px';
        _this.el.style.left=_this.pos.xNew+'px';
    }
    MovableBlock.prototype.close=function(){
        _this.el.remove();
    }

    _this.startMoveBind=_this.startMove.bind(_this);
    _this.movingBind=_this.moving.bind(_this);
    _this.endMoveBind=_this.endMove.bind(_this);
    _this.init()
}
